import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../core/database/prisma.service';
import { PromptBuilderService } from './prompt-builder.service';
import { LlmService } from './llm.service';
import { AiValidationService } from './ai-validation.service';
import { GenerateAiWorkoutDto } from './dto/ai-requests.dto';
import { PlanStatus } from '@prisma/client';

@Injectable()
export class AiWorkoutService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly promptBuilder: PromptBuilderService,
    private readonly llmService: LlmService,
    private readonly validator: AiValidationService,
  ) {}

  /**
   * AI Workout Plan Generation Pipeline
   */
  async generateWorkoutPlan(
    tenantId: string,
    userId: string,
    dto: GenerateAiWorkoutDto,
  ) {
    const profile = await this.prisma.customerProfile.findUnique({
      where: { userId },
    });

    if (!profile) {
      throw new NotFoundException('Customer profile not found');
    }

    const prompt = this.promptBuilder.buildWorkoutPlanPrompt(
      profile,
      dto.durationWeeks || 4,
      dto.specialInstructions,
    );

    const systemPrompt =
      'You are an elite strength & conditioning coach. Always output valid structured JSON conforming to the requested workout schema.';

    const aiResponse = await this.llmService.generateJsonCompletion(systemPrompt, prompt);

    this.validator.validateWorkoutPlan(aiResponse, profile);

    return this.prisma.$transaction(async (tx) => {
      const plan = await tx.workoutPlan.create({
        data: {
          tenantId,
          customerId: userId,
          createdById: userId,
          name: aiResponse.name || 'AI Personalized Workout Split',
          description: aiResponse.description || 'Generated by AI Coach',
          durationWeeks: aiResponse.durationWeeks || 4,
          difficulty: profile.workoutExperience || 'BEGINNER',
          goal: profile.fitnessGoal || 'General Fitness',
          status: PlanStatus.DRAFT,
          isAiGenerated: true,
        },
      });

      for (const day of aiResponse.days) {
        const workoutDay = await tx.workoutDay.create({
          data: {
            workoutPlanId: plan.id,
            dayNumber: day.dayNumber,
            dayName: day.dayName,
            isRestDay: day.isRestDay || false,
            targetDurationMinutes: day.targetDurationMinutes || 45,
            notes: day.notes,
          },
        });

        if (day.exercises && day.exercises.length > 0) {
          for (let i = 0; i < day.exercises.length; i++) {
            const ex = day.exercises[i];

            // Find matching exercise or create default exercise item
            let matchedExercise = await tx.exercise.findFirst({
              where: {
                name: { contains: ex.exerciseName, mode: 'insensitive' },
              },
            });

            if (!matchedExercise) {
              matchedExercise = await tx.exercise.create({
                data: {
                  name: ex.exerciseName,
                  muscleGroup: 'FULL_BODY',
                  isGlobal: true,
                },
              });
            }

            await tx.workoutDayExercise.create({
              data: {
                workoutDayId: workoutDay.id,
                exerciseId: matchedExercise.id,
                orderInDay: ex.orderInDay || i + 1,
                sets: ex.sets || 3,
                reps: ex.reps || 10,
                targetWeightKg: ex.targetWeightKg,
                restTimeSeconds: ex.restTimeSeconds || 60,
                tempo: ex.tempo || '2-0-2-0',
                notes: ex.notes,
              },
            });
          }
        }
      }

      return tx.workoutPlan.findUnique({
        where: { id: plan.id },
        include: {
          days: {
            include: {
              exercises: {
                include: { exercise: true },
              },
            },
          },
        },
      });
    });
  }
}
